### ISSUE TITLE
Add roles for system modules

### ISSUE THREAD

**Issue by devyanikota** [gluster/gluster-ansible#12]
The system roles include:

- [x] backend_setup - A generic backend setup for GlusterFS volume.
- [x] backend_reset - A generic backend reset for GlusterFS volume.
- [x] glusterfs_pv - Create physical volume.
- [x] glusterfs_vg - Create a volume group.
- [x] glusterfs_lv - Create a logical volume.
- [x] mount - mount a logical volume, or a GlusterFS volume.
- [x] umount - umount a logical volume, or a GlusterFS volume.

**Comment by siddharthvipul** [comment]
@devyanikota : Hey, I would like to work on mount & umount.
