### ISSUE TITLE
gluster.cluster: Create a 3-way replicated or 3-way distributed-replicated volume

### ISSUE THREAD

**Issue by sac** [gluster/gluster-ansible#34]
Create a 3-way replicated or 3-way distributed-replicated volume with client side meta-data caching turned on.

* Write an example playbook for the above

**Comment by devyanikota** [comment]
PR #38 fixes this issue.

**Comment by devyanikota** [comment]
PR [gluster/gluster-ansible-cluster/#4](https://github.com/gluster/gluster-ansible-cluster/pull/4) fixes this issue.

**Comment by devyanikota** [comment]
Closing this issue in favour of PR#4.
