### ISSUE TITLE
gluster.cluster: Create an arbitrated or distributed-replicated arbitrated volume

### ISSUE THREAD

**Issue by sac** [gluster/gluster-ansible#35]
Create an arbitrated or distributed-replicated arbitrated volume

* Example playbook for the above

**Comment by devyanikota** [comment]
PR #37 fixes this issue.

**Comment by devyanikota** [comment]
PR [gluster/gluster-ansible-cluster/#4](https://github.com/gluster/gluster-ansible-cluster/pull/4) fixes this issue.

**Comment by devyanikota** [comment]
Closing this issue in favour of PR#4.
