### ISSUE TITLE
[gadmin] Plugin for writing the playbook output to file

### ISSUE THREAD

**Issue by brainfunked** [gluster/gluster-ansible#39]
Gadmin integration strategy is being discussed here: https://github.com/gluster/gadmin/issues/4

Based on my understanding of ansible, it seems that writing a plugin would enable us to get the cleanest integration between gadmin and gluster-ansible. I'm considering the following overall criteria:

- The playbooks shipped by gluster-ansible should be directly usable via gadmin, without requiring any modifications. This means that a handler based functionality would not work, as gluster-ansible playbooks need to function in a normal ansible execution by the user. If the handlers are included in the playbooks that function specifically for gadmin, it would impair gluster-ansible's native functionality.
- Plugin selection is done at runtime via an environment variable. This means that the playbooks can simply be run with or without the plugin and hence serve both normal ansible and gadmin execution, without modifications.
- Plugins are the way ansible enables 'customisation' of the output from a play. Ansible itself ships with plugins for writing to a log file, JSON output etc. However, in the case of gadmin, we need a combination of the two.
- While ansible recommends that plugins be merged into ansible core itself, it does allow plugins to ship with the roles. This means that both gluster-ansible and gadmin can keep on with the development by shipping a plugin with gluster-ansible, till it is integrated in ansible core.

## Required functionality

- Gadmin needs to supply an output file name. This could be done via an environment variable whose value is read by the plugin. If the variable is undefined, the output should be sent directly to stdout.
- The plugin needs to output in a well-defined parsable format such as JSON or YAML.
- A schema for the output needs to be maintained such that the parsing code can be implemented in gadmin. To start with, it would be necessary to define the following fields:
  - task name
  - success or failure
  - message
  - dictionary of variables and values that may be relevant to the end user

The actual output message and variables need to be decided per-playbook. However, the plugin itself needs to provide the infrastructure first.

**Comment by sac** [comment]
No longer relevant. If so please re-open with a reason.
