### ISSUE TITLE
[gadmin] Startup checks to validate the availability and configuration of gluster-ansible

### ISSUE THREAD

**Issue by brainfunked** [gluster/gluster-ansible#40]
How would gadmin validate that all the necessary gluster-ansible roles and playbooks are installed on the system?

**Comment by sac** [comment]
gadmin can check the rpms:

```
[sac@dhcp35-44 gluster-ansible]$ yum list gluster-ansible\*
Installed Packages
gluster-ansible.noarch                                                                                       0.1-1.fc27                                                                               @@commandline
gluster-ansible-features.noarch                                                                              0.1-1.fc27                                                                               @@commandline
gluster-ansible-infra.noarch                                                                                 0.1-1.fc27                                                                               @@commandline
[sac@dhcp35-44 gluster-ansible]$ 
```
Or check: /etc/ansible/roles/gluster.*

**Comment by brainfunked** [comment]
RPM checks are platform specific though. Is it possible to list the ansible roles installed and available on the system?

**Comment by brainfunked** [comment]
Also need to verify whether all the necessary ansible commands are installed on the system. Which commands should be checked for?

**Comment by sac** [comment]
If ansible is installed the necessary executables are available. We use only ansible-playbook. ansible-galaxy is to check which roles are installed, we don't usually use it in gluster-ansible.

**Comment by sac** [comment]
All questions are answered in the issue.
